# Generated by Django 3.0.8 on 2020-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание', blank=True)),
                ('price', models.FloatField(verbose_name='Цена')),
                ('number_purchases', models.IntegerField(default=0, verbose_name='Кол-во покупок')),
                ('availability', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
    ]
