# Generated by Django 3.0.8 on 2020-07-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200710_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought',
            field=models.IntegerField(verbose_name='Куплено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
