# Generated by Django 3.0.8 on 2020-07-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200725_2036'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_order', to='order.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_order', to='product.Product', verbose_name='Товар'),
        ),
    ]
